name: Build APK
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Create keystore
        run: |
          cd simple_live_app/android
          keytool -genkey -v -keystore release.keystore -alias release -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=,OU=,O=,L=,S=,C="
          echo "storeFile=release.keystore" > key.properties
          echo "storePassword=android" >> key.properties
          echo "keyPassword=android" >> key.properties
          echo "keyAlias=release" >> key.properties
      - name: Build APK
        run: |
          cd simple_live_app
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: simple-live-app
          path: simple_live_app/build/app/outputs/apk/release/*.apk
